import type { SplitString } from './split-identifier';

export default [
  'key',
  'ref',
  'suppress hydration warning',
  'as',
  'id',
  'name',
  'data',
  'data *',
  'test *',
  'class',
  'class name',
  'slot',
  'src',
  'src doc',
  'src set',
  'src lang',
  'alt',
  'poster',
  'decoding',
  'auto play',
  'controls',
  'loop',
  'muted',
  'plays inline',
  'preload',
  'kind',
  'default',
  'access key',
  'tab index',
  'content editable',
  'suppress content editable warning',
  'lang',
  'language',
  'translate',
  'dir',
  'dir name',
  'title',
  'draggable',
  'hidden',
  'role',
  'spell check',
  'auto capitalize',
  'item prop',
  'char set',
  'content',
  'http equiv',
  'csp',
  'href',
  'href lang',
  'rel',
  'target',
  'cross origin',
  'integrity',
  'loading',
  'referrer policy',
  'ping',
  'download',
  'media',
  'intrinsicsize',
  'sizes',
  'use map',
  'all',
  'display',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'offset',
  'offset anchor',
  'offset distance',
  'offset path',
  'offset position',
  'offset rotate',
  'grid',
  'grid template rows',
  'grid template columns',
  'grid template areas',
  'grid auto rows',
  'grid auto columns',
  'grid auto flow',
  'column gap',
  'row gap',
  'grid area',
  'grid row',
  'grid row start',
  'grid row end',
  'grid column',
  'grid column start',
  'grid column end',
  'grid template',
  'flex',
  'flex grow',
  'flex shrink',
  'flex basis',
  'flex direction',
  'flex flow',
  'flex wrap',
  'box decoration break',
  'place content',
  'align content',
  'justify content',
  'place items',
  'align items',
  'justify items',
  'place self',
  'align self',
  'justify self',
  'vertical align',
  'baseline source',
  'order',
  'float',
  'clear',
  'shape margin',
  'shape outside',
  'shape image threshold',
  'orphans',
  'gap',
  'columns',
  'column fill',
  'column rule',
  'column rule width',
  'column rule style',
  'column rule color',
  'column width',
  'column span',
  'column count',
  'break before',
  'break after',
  'break inside',
  'page',
  'page break before',
  'page break after',
  'page break inside',
  'transform',
  'transform box',
  'transform origin',
  'transform style',
  'rotate',
  'scale',
  'perspective',
  'perspective origin',
  'appearance',
  'visibility',
  'content visibility',
  'opacity',
  'z index',
  'paint order',
  'mix blend mode',
  'backface visibility',
  'backdrop filter',
  'clip path',
  'mask',
  'mask border',
  'mask border outset',
  'mask border repeat',
  'mask border slice',
  'mask border source',
  'mask border width',
  'mask image',
  'mask mode',
  'mask position',
  'mask size',
  'mask repeat',
  'mask origin',
  'mask clip',
  'mask composite',
  'mask type',
  'filter',
  'animation',
  'animation composition',
  'animation duration',
  'animation timing function',
  'animation delay',
  'animation iteration count',
  'animation direction',
  'animation fill mode',
  'animation play state',
  'animation name',
  'transition',
  'transition behavior',
  'transition delay',
  'transition duration',
  'transition property',
  'transition timing function',
  'will change',
  'counter increment',
  'counter reset',
  'counter set',
  'cursor',
  'box sizing',
  'contain',
  'contain intrinsic height',
  'contain intrinsic size',
  'contain intrinsic width',
  'container',
  'container name',
  'container type',
  'margin',
  'm',
  'margin top',
  'mt',
  'margin right',
  'mr',
  'margin bottom',
  'mb',
  'margin left',
  'ml',
  'margin inline',
  'margin inline start',
  'margin inline end',
  'margin block',
  'margin block start',
  'margin block end',
  'mx',
  'my',
  'margin width',
  'margin height',
  'inset',
  'inset block',
  'inset block end',
  'inset block start',
  'inset inline',
  'inset inline end',
  'inset inline start',
  'outline',
  'outline color',
  'outline style',
  'outline width',
  'outline offset',
  'box shadow',
  'border top',
  'border right',
  'border bottom',
  'border left',
  'border width',
  'border top width',
  'border right width',
  'border bottom width',
  'border left width',
  'border style',
  'border top style',
  'border right style',
  'border bottom style',
  'border left style',
  'border color',
  'border top color',
  'border right color',
  'border bottom color',
  'border left color',
  'border radius',
  'border top right radius',
  'border top left radius',
  'border bottom right radius',
  'border bottom left radius',
  'border inline',
  'border inline width',
  'border inline style',
  'border inline color',
  'border inline start',
  'border inline start width',
  'border inline start style',
  'border inline start color',
  'border inline end',
  'border inline end width',
  'border inline end style',
  'border inline end color',
  'border block',
  'border block width',
  'border block style',
  'border block color',
  'border block start',
  'border block start width',
  'border block start style',
  'border block start color',
  'border block end',
  'border block end width',
  'border block end style',
  'border block end color',
  'border image',
  'border image source',
  'border image slice',
  'border image width',
  'border image outset',
  'border image repeat',
  'border collapse',
  'border spacing',
  'border start start radius',
  'border start end radius',
  'border end start radius',
  'border end end radius',
  'background',
  'background image',
  'background position',
  'background size',
  'background repeat',
  'background origin',
  'background clip',
  'background attachment',
  'background color',
  'bgcolor',
  'background blend mode',
  'background position x',
  'background position y',
  'isolation',
  'padding',
  'p',
  'padding top',
  'pt',
  'padding right',
  'pr',
  'padding bottom',
  'pb',
  'padding left',
  'pl',
  'padding inline',
  'padding inline start',
  'padding inline end',
  'padding block',
  'padding block start',
  'padding block end',
  'px',
  'py',
  'image orientation',
  'image rendering',
  'aspect ratio',
  'width',
  'w',
  'min width',
  'min w',
  'max width',
  'max w',
  'height',
  'h',
  'min height',
  'min h',
  'max height',
  'max h',
  'webkit line clamp',
  'webkit text fill color',
  'webkit text stroke',
  'webkit text stroke color',
  'webkit text stroke width',
  'inline size',
  'min inline size',
  'max inline size',
  'block size',
  'min block size',
  'max block size',
  'table layout',
  'caption side',
  'empty cells',
  'overflow',
  'overflow anchor',
  'overflow block',
  'overflow clip margin',
  'overflow inline',
  'overflow x',
  'overflow y',
  'overscroll behavior',
  'overscroll behavior block',
  'overscroll behavior inline',
  'overscroll behavior x',
  'overscroll behavior y',
  'resize',
  'object fit',
  'object position',
  'scroll behavior',
  'scroll margin',
  'scroll margin block',
  'scroll margin block end',
  'scroll margin block start',
  'scroll margin bottom',
  'scroll margin inline',
  'scroll margin inline end',
  'scroll margin inline start',
  'scroll margin left',
  'scroll margin right',
  'scroll margin top',
  'scroll padding',
  'scroll padding block',
  'scroll padding block end',
  'scroll padding block start',
  'scroll padding bottom',
  'scroll padding inline',
  'scroll padding inline end',
  'scroll padding inline start',
  'scroll padding left',
  'scroll padding right',
  'scroll padding top',
  'scroll snap align',
  'scroll snap stop',
  'scroll snap type',
  'scrollbar color',
  'scrollbar gutter',
  'scrollbar width',
  'touch action',
  'pointer events',
  'quotes',
  'hanging punctuation',
  'color',
  'color interpolation',
  'color interpolation filters',
  'accent color',
  'print color adjust',
  'forced color adjust',
  'color scheme',
  'caret color',
  'font',
  'font style',
  'font variant',
  'font weight',
  'font stretch',
  'font size',
  'size adjust',
  'line height',
  'font family',
  'font display',
  'font kerning',
  'font language override',
  'font optical sizing',
  'font palette',
  'font size adjust',
  'font synthesis',
  'font synthesis weight',
  'font synthesis style',
  'font synthesis small caps',
  'font synthesis position',
  'font variant alternates',
  'font variant caps',
  'font variant east asian',
  'font variant emoji',
  'font variant ligatures',
  'font variant numeric',
  'font variant position',
  'font variation settings',
  'font feature settings',
  'ascent override',
  'descent override',
  'line gap override',
  'hyphens',
  'hyphenate character',
  'letter spacing',
  'line break',
  'list style',
  'list style type',
  'list style image',
  'list style position',
  'writing mode',
  'direction',
  'unicode bidi',
  'unicode range',
  'user select',
  'ruby position',
  'math depth',
  'math style',
  'text combine upright',
  'text align',
  'text align last',
  'text decoration',
  'text decoration line',
  'text decoration style',
  'text decoration color',
  'text decoration thickness',
  'text decoration skip ink',
  'text emphasis',
  'text emphasis style',
  'text emphasis color',
  'text emphasis position',
  'text indent',
  'text justify',
  'text underline position',
  'text underline offset',
  'text orientation',
  'text overflow',
  'text rendering',
  'text shadow',
  'text transform',
  'text wrap',
  'white space',
  'white space collapse',
  'word break',
  'word spacing',
  'overflow wrap',
  'tab size',
  'widows',
  'type',
  'default value',
  'value',
  'selected value',
  'placeholder',
  'accept',
  'auto complete',
  'capture',
  'input mode',
  'list',
  'multiple',
  'default checked',
  'checked',
  'disabled',
  'required',
  'read only',
  'pattern',
  'min',
  'max',
  'step',
  'min length',
  'max length',
  'size',
  'wrap',
  'enter key hint',
  'selected',
  'action',
  'method',
  'accept charset',
  'enc type',
  'no validate',
  'form',
  'form action',
  'form enc type',
  'form method',
  'form no validate',
  'form target',
  'for',
  'html for',
  'label',
  'summary',
  'border',
  'align',
  'cols',
  'rows',
  'col span',
  'row span',
  'headers',
  'scope',
  'span',
  'shape',
  'coords',
  'ismap',
  'reversed',
  'start',
  'allow',
  'sandbox',
  'low',
  'high',
  'optimum',
  'async',
  'defer',
  'scoped',
  'date time',
  'cite',
  'open',
  'version',
  'base profile',
  'xmlns',
  'xmlns xlink',
  'xml base',
  'xml lang',
  'xml space',
  'abbr',
  'class id',
  'about',
  'datatype',
  'prefix',
  'property',
  'resource',
  'typeof',
  'vocab',
  'is',
  'view box',
  'preserve aspect ratio',
  'view target',
  'zoom and pan',
  'x',
  'y',
  'x1',
  'y1',
  'x2',
  'y2',
  'z',
  'cx',
  'cy',
  'r',
  'rx',
  'ry',
  'radius',
  'points',
  'd',
  'path',
  'path length',
  'fx',
  'fy',
  'dx',
  'dy',
  'gradient transform',
  'pattern transform',
  'vector effect',
  'origin',
  'horiz origin x',
  'vert origin x',
  'vert origin y',
  'stroke',
  'stroke width',
  'stroke opacity',
  'stroke dasharray',
  'stroke dashoffset',
  'stroke linecap',
  'stroke linejoin',
  'stroke miterlimit',
  'fill',
  'fill opacity',
  'fill rule',
  'clip',
  'clip rule',
  'clip path units',
  'stop color',
  'stop opacity',
  'flood color',
  'flood opacity',
  'lighting color',
  'color profile',
  'preserve alpha',
  'color rendering',
  'marker start',
  'marker mid',
  'marker end',
  'marker width',
  'marker height',
  'marker units',
  'orient',
  'orientation',
  'elevation',
  'filter res',
  'filter units',
  'primitive units',
  'kernel matrix',
  'kernel unit length',
  'g1',
  'g2',
  'in',
  'in2',
  'k',
  'k1',
  'k2',
  'k3',
  'k4',
  'result',
  'std deviation',
  'bias',
  'exponent',
  'intercept',
  'divisor',
  'x channel selector',
  'y channel selector',
  'diffuse constant',
  'specular constant',
  'specular exponent',
  'surface scale',
  'seed',
  'limiting cone angle',
  'gradient units',
  'pattern units',
  'pattern content units',
  'spread method',
  'mask units',
  'mask content units',
  'calc mode',
  'key points',
  'key splines',
  'key times',
  'attribute name',
  'attribute type',
  'additive',
  'accumulate',
  'decelerate',
  'from',
  'to',
  'by',
  'begin',
  'dur',
  'end',
  'restart',
  'repeat count',
  'repeat dur',
  'auto reverse',
  'speed',
  'mode',
  'values',
  'text anchor',
  'text length',
  'length adjust',
  'dominant baseline',
  'alignment baseline',
  'baseline shift',
  'kerning',
  'glyph orientation horizontal',
  'glyph orientation vertical',
  'glyph ref',
  'glyph name',
  'format',
  'unicode',
  'arabic form',
  'hanging',
  'alphabetic',
  'ideographic',
  'mathematical',
  'accent height',
  'ascent',
  'azimuth',
  'bbox',
  'cap height',
  'descent',
  'horiz adv x',
  'vert adv y',
  'overline position',
  'overline thickness',
  'panose1',
  'base frequency',
  'num octaves',
  'stitch tiles',
  'edge mode',
  'amplitude',
  'points at x',
  'points at y',
  'points at z',
  'u1',
  'u2',
  'slope',
  'stemh',
  'stemv',
  'strikethrough position',
  'strikethrough thickness',
  'underline position',
  'underline thickness',
  'units per em',
  'v alphabetic',
  'v hanging',
  'v ideographic',
  'v mathematical',
  'widths',
  'x height',
  'enable background',
  'external resources required',
  'required extensions',
  'required features',
  'system language',
  'table values',
  'shape rendering',
  'rendering intent',
  'target x',
  'target y',
  'ref x',
  'ref y',
  'allow reorder',
  'string',
  'spacing',
  'start offset',
  'focusable',
  'allow full screen',
  'allow popups',
  'allow transparency',
  'auto correct',
  'auto focus',
  'auto save',
  'autosize',
  'blinkfeatures',
  'cell padding',
  'cell spacing',
  'challenge',
  'content script type',
  'content style type',
  'context menu',
  'controls list',
  'disable blink features',
  'disable guest resize',
  'disable picture in picture',
  'disable remote playback',
  'disable web security',
  'fetch priority',
  'frame',
  'frame border',
  'fr',
  'partition',
  'guest instance',
  'http referrer',
  'image sizes',
  'image src set',
  'inert',
  'inlist',
  'item id',
  'item ref',
  'item scope',
  'item type',
  'key params',
  'key type',
  'manifest',
  'media group',
  'no module',
  'nonce',
  'node integration',
  'plugins',
  'popover',
  'popover target',
  'popover target action',
  'operator',
  'precedence',
  'radio group',
  'results',
  'rules',
  'scrolling',
  'seamless',
  'security',
  'unselectable',
  'rev',
  'local',
  'user agent',
  'web preferences',
  'valign',
  'wmode',
  'xlink href',
  'xlink role',
  'xlink arcrole',
  'xlink title',
  'xlink type',
  'xlink show',
  'xlink actuate',
  'dangerously set inner html',
  'on click',
  'on click capture',
  'on double click',
  'on double click capture',
  'on aux click',
  'on aux click capture',
  'on key down',
  'on key down capture',
  'on key up',
  'on key up capture',
  'on key press',
  'on key press capture',
  'on focus',
  'on focus capture',
  'on blur',
  'on blur capture',
  'on close',
  'on cancel',
  'on change',
  'on change capture',
  'on before input',
  'on before input capture',
  'on input',
  'on input capture',
  'on submit',
  'on submit capture',
  'on reset',
  'on reset capture',
  'on invalid',
  'on invalid capture',
  'on mouse down',
  'on mouse down capture',
  'on mouse up',
  'on mouse up capture',
  'on mouse enter',
  'on mouse leave',
  'on mouse over',
  'on mouse over capture',
  'on mouse out',
  'on mouse out capture',
  'on mouse move',
  'on mouse move capture',
  'on touch start',
  'on touch start capture',
  'on touch end',
  'on touch end capture',
  'on touch move',
  'on touch move capture',
  'on touch cancel',
  'on touch cancel capture',
  'on pointer down',
  'on pointer down capture',
  'on pointer up',
  'on pointer up capture',
  'on pointer move',
  'on pointer move capture',
  'on pointer cancel',
  'on pointer cancel capture',
  'on pointer enter',
  'on pointer leave',
  'on pointer over',
  'on pointer over capture',
  'on pointer out',
  'on pointer out capture',
  'on got pointer capture',
  'on got pointer capture capture',
  'on lost pointer capture',
  'on lost pointer capture capture',
  'on drag start',
  'on drag start capture',
  'on drag end',
  'on drag end capture',
  'on drag',
  'on drag capture',
  'on drag enter',
  'on drag enter capture',
  'on drag leave',
  'on drag leave capture',
  'on drag exit',
  'on drag exit capture',
  'on drag over',
  'on drag over capture',
  'on drop',
  'on drop capture',
  'on copy',
  'on copy capture',
  'on cut',
  'on cut capture',
  'on paste',
  'on paste capture',
  'on load',
  'on load capture',
  'on error',
  'on error capture',
  'on abort',
  'on abort capture',
  'on can play',
  'on can play capture',
  'on can play through',
  'on can play through capture',
  'on load start',
  'on load start capture',
  'on loaded metadata',
  'on loaded metadata capture',
  'on loaded data',
  'on loaded data capture',
  'on duration change',
  'on duration change capture',
  'on play',
  'on play capture',
  'on pause',
  'on pause capture',
  'on playing',
  'on playing capture',
  'on progress',
  'on progress capture',
  'on rate change',
  'on rate change capture',
  'on seeked',
  'on seeked capture',
  'on seeking',
  'on seeking capture',
  'on emptied',
  'on emptied capture',
  'on encrypted',
  'on encrypted capture',
  'on stalled',
  'on stalled capture',
  'on suspend',
  'on suspend capture',
  'on waiting',
  'on waiting capture',
  'on ended',
  'on ended capture',
  'on volume change',
  'on volume change capture',
  'on time update',
  'on time update capture',
  'on resize',
  'on resize capture',
  'on animation start',
  'on animation start capture',
  'on animation end',
  'on animation end capture',
  'on animation iteration',
  'on animation iteration capture',
  'on transition run',
  'on transition run capture',
  'on transition start',
  'on transition start capture',
  'on transition end',
  'on transition end capture',
  'on transition cancel',
  'on transition cancel capture',
  'on composition start',
  'on composition start capture',
  'on composition update',
  'on composition update capture',
  'on composition end',
  'on composition end capture',
  'on scroll',
  'on scroll capture',
  'on wheel',
  'on wheel capture',
  'on before toggle',
  'on toggle',
  'on context menu',
  'on context menu capture',
  'on select',
  'on select capture',
  'style',
  'children',
  'aria *',
] as SplitString[];
